Fix highlight of multiline string in diagnostic
The following source:

  {
    ---
    foo
    ---
  }

would cause this error previously:

  Parse error at line 2:

    ---
    ^~~~~~~~~~~~~~~
  Error: Parse error in statement: expected import, return, assignment,
  block, or put.

Note how the line of ~~~ is too long; it spans the lenght of the entire
string literal, but we should only print it for the current line. This
commit fixes that.